### ISSUE TITLE
D7.4.1 ModelWriter-ITEA website

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#116]
This is an issue of the task : T7.4	ModelWriter-ITEA Consortium Website (OBEO + UNIT)
--------------------------------------------------------------------------------------------------------------------------

The main support mechanism will be the ModelWriter-ITEA consortium project website (D7.4.1). This will be developed to be widely and easily accessible and to provide all public outputs and information from the project. 
The site will contain public part containing information about the project, public results and national contacts whereas the private and secure part will include private information will be restricted for members
This artefact will provide a single focus for all ModelWriter-ITEA consortium activities (including workshops) and will allow a wide range of users to learn about and take advantage of the project's outputs.

**Comment by mrostren** [comment]
Hello Ferhat /CC @ferhaterata 

Sorry for the late reply,
We are working on the website and will generate the website using Joomla which is much faster to do on our side.

We have several issues about the website link...
* do you validate that the link to use as an access is  **www.modelwriter.eu** ? 
* in fact we wonder if you have already purchase the domain ?!
* the admin accesses will be secured (https)
I suggest to define later the admins and contributors on the website.

For information, I will create an additional github issue for the logo in the WP7 repository do you know if we have any deliverable related to the logo ? I suggest to link it to an existing deliverable like the currrent one D7.4.1 ModelWriter-ITEA website #116
(see ModelWriter/WP7#13)

Regards

**Comment by mrostren** [comment]
an email is sent today to @ferhaterata  and @m-challenger about the website public Ip address and about the secured access.

**Comment by ferhaterata** [comment]
we will answer the email as soon as we finish today's tasks.

**Comment by m-challenger** [comment]
- UNIT will configure the DNS to publish the website
- OBEO will provide content

**Comment by m-challenger** [comment]
The website is available in Obeo domain at: http://modelwriter.obeo.fr

@ModelWriter/consortium
