### ISSUE TITLE
D7.5.2 Research-oriented talk about the principles and benefits of the ModelWriter-ITEA approach and tooling

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#118]

**Comment by m-challenger** [comment]
- UYMK conference presentation
- ATSEN conference presentation

**Comment by m-challenger** [comment]
UNIT has finalized the document. 
Please feel free to check and modify, if necessary. 
You can find the document at:
https://github.com/ModelWriter/Deliverables/blob/master/WP7/D7.5.2-Research-oriented%20talk%20about%20the%20principles%20and%20benefits%20of%20the%20ModelWriter-ITEA%20approach%20and%20tooling.docx

@ModelWriter/consortium

**Comment by ferhaterata** [comment]
**COST Action IC1404 Multi-Paradigm Modelling for Cyber-Physical Systems** Gdansk Management Committee and Working Group Meetings  (14-16 September 2016 )

[_Co-organized by the Mazovia Branch of the Polish Information Processing Society and the IEEE Poland Section Chapter of the Computer Society._ ] (http://mpm4cps.eu/workshops/16.09.14-16.Gdansk/)

https://github.com/ModelWriter/Deliverables/blob/master/WP7/D7.5.2%20Research-oriented%20Talk_MPM4CPS_20160915.pdf

@ModelWriter/consortium
