### ISSUE TITLE
D3.1.1 Review of model-to-model transformation approaches and technologies

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#33]
- [ ] Moflon: Triple Graph Grammars (TGGs) for model synchronization (bidirectional transformations)(http://www.emoflon.org/emoflon/documentation/)
 - [A Case Study Based Comparison of ATL and SDM](http://link.springer.com/chapter/10.1007%2F978-3-642-34176-2_18)
- [ ] ATL

**Comment by m-challenger** [comment]
Hi all,
The draft version of D3.1.1 is initiated in github at: 
https://github.com/ModelWriter/Deliverables/tree/master/WP3
Please feel free to contribute in it.

**Comment by m-challenger** [comment]
Hi all, 
The D3.1.1 deliverable is finalized and its document is available online at: 
https://github.com/ModelWriter/Deliverables/tree/master/WP3

**Comment by ejuliot** [comment]
In the document "D3.1.1 Review of model-to-model transformation approaches and technologies", you said "ATL, Atlas Transformation Language". It was the previous name of this project. Now, it is "ATL Transformation Language".

You miss one major technology for M2M transformation: classical Java classes with the usage of EMF APIs.

**Comment by m-challenger** [comment]
Etienne, I have addressed your comments in the document. Thanks!
@ModelWriter/consortium 
@ejuliot
