### ISSUE TITLE
D3.2.1 M2M Transformation Framework architectural design document

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#34]
https://github.com/ModelWriter/Deliverables/blob/master/WP3/D3.2.1%20M2M%20Transformation%20Framework%20architectural%20design%20document.docx?raw=true

**Comment by m-challenger** [comment]
Hi all,
The draft version of D3.2.1 is initiated in github at:
https://github.com/ModelWriter/Deliverables/tree/master/WP3
Please feel free to contribute in it.

**Comment by m-challenger** [comment]
The new architecture of WP3 will be documented.

**Comment by m-challenger** [comment]
This document is finalized and uploaded into GitHub.

@ModelWriter/consortium
