### ISSUE TITLE
D4.2.1 Interface Control Document (ICD)

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#58]
https://github.com/ModelWriter/Deliverables/blob/master/WP4/D4.2.1%20Interface%20Control%20Document%20(ICD).docx?raw=true

**Comment by m-challenger** [comment]
Hi all,
The draft version of D4.2.1 is initiated in github at:
https://github.com/ModelWriter/Deliverables/tree/master/WP4
Please feel free to contribute in it.

**Comment by m-challenger** [comment]
- LORIA will provide some interface signatures

**Comment by mariem-m** [comment]
I have just uploaded the interface.

**Comment by m-challenger** [comment]
This document is finalized.

@ModelWriter/consortium
