### ISSUE TITLE
D1.3.3 Corpus for French Use Cases (Private)

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#7]

**Comment by annemonceaux** [comment]
The private corpus is a set of SIDP documents. This private corpus will be provided by Airbus SAS to Airbus Group SAS and other French partners LORIA and OBEO under NDA condition. The NDA is currently being prepared by Airbus SAS and has been transferred to Airbus Group SAS for signature the 13th of February.

For initial step in the project, we will start with 1 SIDP that concerns ATA 38 (Water Waste System). the pdf version of the document is available for AIrbus Group SAS use so far; so we can work on the domain meta model.
This document will be provided in MSWord format (with "visual" models included as pictures). Among the  "visual" models that are "pictured" in the document, the tables will be provided in numeric format in a tabular format or in Excel. Hopefully these corpora will be available in February.

**Comment by m-challenger** [comment]
Part of the corpus data is provided by the partners. However, some of the other partners have not decided on their corpus cases. 
Anyway, as some of the partners have not also decided for the privacy or publicity of the data, all of the corpus data is kept in a private repository in the GitHub.

@ModelWriter/consortium
