### ISSUE TITLE
D6.5.2-1 Automated Acceptance Tests (release 1)

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#97]

**Comment by m-challenger** [comment]
- Each partner should provide unit test for their own part. 
      - JUnit can be used for this test.
- There is a need for integration/functional test
     - Can be realized by JUnit test and RCPTT (Rich Client Platform Testing Tool)

**Comment by ejuliot** [comment]
This deliverable is very late: it should be released for M12.

What is the current status? Have you started to write some functional tests?

Just a comment about @m-challenger last comment: as this deliverable is focus on acceptance, only integration/function tests are relevant, not unit tests.

If writing RCPTT tests is too complex for a first step, it could be possible to focus your effort on writing these functional tests in english. It will be useful as specification for later implementations.

**Comment by ejuliot** [comment]
Any news about this deliverable? It was plan for M12 and we are at M24 !!!
And didn't see any activity from the task leader. It start to be a critical issue.

**Comment by ylussaud** [comment]
403 tests can be found here:
https://github.com/ModelWriter/Source/tree/ITEA_RELEASE_2/tests
